spring:
  application:
    name: agenttools
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/agenttoolsdb;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
