spring:
  application:
    name: agenttools
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/agenttoolsdb;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  sakila-datasource:
    jdbc-url: jdbc:h2:file:./src/main/resources/data/sakila;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  files:
    cve:
      path: ../data/cve
    policies:
      path: ../data/policies
    uploads:
      path: ${data.uploads.path}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-3.5-turbo
          max-tokens: 256
